/**
 * Script de seed temporaire — à supprimer après démo.
 * Appeler seedDemoMission() depuis n'importe quel composant.
 */
import { supabase } from "@/integrations/supabase/client";

export async function seedDemoMission(): Promise<string> {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  // ─── 1. Mission ────────────────────────────────────────────
  const { data: mission, error: mErr } = await (supabase.from("missions") as any)
    .insert({
      consultant_id: user.id,
      client_nom: "Sophie Martin",
      client_organisation: "Métropole de Lyon",
      client_secteur: "public",
      client_taille: "enterprise",
      client_contact_nom: "Jean-Pierre Duval",
      client_contact_email: "jp.duval@grandlyon.fr",
      client_contact_poste: "DGA Transformation numérique",
      objectif_mission:
        "Cartographier le potentiel IA des services administratifs et identifier les quick-wins d'automatisation pour 2 400 agents",
      contexte_si:
        "DSI de 45 personnes. Infrastructure hybride M365 E3 + apps métier legacy (Sedit, Ciril, Ixbus). Migration cloud en cours. Power Platform déployée mais sous-utilisée.",
      contraintes: [
        "Conformité RGPD stricte (données citoyens)",
        "Validation DPO obligatoire",
        "Budget plafonné à 150k€ sur 18 mois",
        "Pas de données sensibles dans le cloud US",
      ],
      outils_actuels: [
        "M365 E3",
        "SharePoint Online",
        "Power Automate (licence basique)",
        "Sedit RH",
        "Ciril Finances",
        "Ixbus délibérations",
      ],
      budget_indicatif: "80-120k€ première phase",
      statut: "en_cours",
      date_debut: "2026-02-15",
      date_livraison_prevue: "2026-05-30",
    })
    .select()
    .single();

  if (mErr) throw mErr;
  const mId = mission.id;

  // ─── 2. Entretiens ────────────────────────────────────────
  const entretiens = [
    {
      mission_id: mId,
      service_nom: "Direction des Ressources Humaines",
      metiers: ["Gestionnaire paie", "Chargé de recrutement", "Responsable formation"],
      nb_personnes: 8,
      interlocuteur_nom: "Amélie Bertrand",
      interlocuteur_poste: "DRH adjointe",
      date_entretien: "2026-03-05",
      mode: "live",
      statut: "termine",
      notes_consultant:
        "Service très demandeur. Forte douleur sur la paie et le recrutement. Bonne maturité digitale.",
      resultats: [
        {
          metier: "Gestionnaire paie",
          score_global: 72,
          heures_economisees_semaine: 6.5,
          taches: [
            {
              nom: "Saisie des éléments variables de paie",
              categorie: "automatisable",
              solution: "Power Automate + Forms pour collecte puis injection Sedit",
              type_outil: "Automatisation No-Code",
              ecosysteme: "M365_PowerAutomate",
              temps_gagne_heures_semaine: 3,
              niveau_accompagnement: "guide",
              score_criteres: 4.2,
              complexite: "moyenne",
              temps_mise_en_place_jours: 12,
              prerequis: ["Licence Power Automate premium", "Connecteur Sedit API"],
            },
            {
              nom: "Contrôle pré-paie mensuel",
              categorie: "partiellement_automatisable",
              solution: "Script Python de détection d'anomalies + dashboard Power BI",
              type_outil: "Script personnalisé",
              ecosysteme: "Python_Script",
              temps_gagne_heures_semaine: 2,
              niveau_accompagnement: "consultant",
              score_criteres: 3.8,
              complexite: "elevee",
              temps_mise_en_place_jours: 20,
              prerequis: ["Accès base Sedit en lecture", "Environnement Python hébergé"],
            },
            {
              nom: "Réponses aux questions paie des agents",
              categorie: "automatisable",
              solution: "Chatbot M365 Copilot entraîné sur la base documentaire RH",
              type_outil: "Copilot / Assistant IA",
              ecosysteme: "M365_Copilot",
              temps_gagne_heures_semaine: 1.5,
              niveau_accompagnement: "guide",
              score_criteres: 4.5,
              complexite: "faible",
              temps_mise_en_place_jours: 5,
              prerequis: ["Licence M365 Copilot", "Base documentaire RH structurée sur SharePoint"],
            },
          ],
        },
      ],
    },
    {
      mission_id: mId,
      service_nom: "Direction des Finances",
      metiers: ["Contrôleur de gestion", "Comptable public"],
      nb_personnes: 5,
      interlocuteur_nom: "Marc Lefebvre",
      interlocuteur_poste: "Directeur financier",
      date_entretien: "2026-03-12",
      mode: "live",
      statut: "termine",
      notes_consultant:
        "Processus très manuels, beaucoup de copier-coller entre Ciril et Excel. Le directeur est sceptique mais les équipes sont motivées.",
      resultats: [
        {
          metier: "Contrôleur de gestion",
          score_global: 68,
          heures_economisees_semaine: 5,
          taches: [
            {
              nom: "Consolidation budgétaire trimestrielle",
              categorie: "automatisable",
              solution: "Power Automate extraction Ciril + consolidation Power BI",
              type_outil: "Automatisation No-Code",
              ecosysteme: "M365_PowerAutomate",
              temps_gagne_heures_semaine: 3,
              niveau_accompagnement: "consultant",
              score_criteres: 4.0,
              complexite: "elevee",
              temps_mise_en_place_jours: 25,
              prerequis: ["API Ciril Finances", "Licence Power BI Pro"],
            },
            {
              nom: "Tableaux de bord direction générale",
              categorie: "automatisable",
              solution: "Dashboard Power BI connecté aux sources Ciril et Excel partagés",
              type_outil: "Automatisation No-Code",
              ecosysteme: "M365_PowerAutomate",
              temps_gagne_heures_semaine: 2,
              niveau_accompagnement: "guide",
              score_criteres: 3.5,
              complexite: "moyenne",
              temps_mise_en_place_jours: 10,
              prerequis: ["Licence Power BI Pro", "Données budgétaires sur SharePoint"],
            },
          ],
        },
      ],
    },
    {
      mission_id: mId,
      service_nom: "Direction de la Communication",
      metiers: ["Community manager", "Chargé de communication interne"],
      nb_personnes: 4,
      interlocuteur_nom: "Clara Nguyen",
      interlocuteur_poste: "Directrice communication",
      date_entretien: "2026-03-19",
      mode: "live",
      statut: "termine",
      notes_consultant:
        "Équipe créative, très ouverte à l'IA générative. Besoin urgent sur la veille presse et les réseaux sociaux.",
      resultats: [
        {
          metier: "Community manager",
          score_global: 81,
          heures_economisees_semaine: 7,
          taches: [
            {
              nom: "Veille presse et réseaux sociaux",
              categorie: "automatisable",
              solution: "Agent IA de veille avec alertes Teams",
              type_outil: "Agent IA",
              ecosysteme: "Agent_IA",
              temps_gagne_heures_semaine: 3,
              niveau_accompagnement: "consultant",
              score_criteres: 4.6,
              complexite: "elevee",
              temps_mise_en_place_jours: 30,
              prerequis: ["Accès API réseaux sociaux", "Webhook Teams"],
            },
            {
              nom: "Rédaction posts réseaux sociaux",
              categorie: "partiellement_automatisable",
              solution: "Copilot avec templates de marque territoriale",
              type_outil: "Copilot / Assistant IA",
              ecosysteme: "M365_Copilot",
              temps_gagne_heures_semaine: 2.5,
              niveau_accompagnement: "express",
              score_criteres: 4.0,
              complexite: "faible",
              temps_mise_en_place_jours: 3,
              prerequis: ["Licence M365 Copilot"],
            },
            {
              nom: "Revue de presse quotidienne",
              categorie: "automatisable",
              solution: "N8N scraping + résumé LLM + envoi Teams",
              type_outil: "Workflow N8N",
              ecosysteme: "N8N",
              temps_gagne_heures_semaine: 1.5,
              niveau_accompagnement: "guide",
              score_criteres: 3.8,
              complexite: "moyenne",
              temps_mise_en_place_jours: 8,
              prerequis: ["Instance N8N hébergée", "Accès flux RSS sources presse"],
            },
          ],
        },
      ],
    },
    {
      mission_id: mId,
      service_nom: "Direction Juridique",
      metiers: ["Juriste marchés publics", "Responsable contentieux"],
      nb_personnes: 3,
      interlocuteur_nom: "Philippe Roche",
      interlocuteur_poste: "Directeur juridique",
      date_entretien: "2026-04-02",
      mode: "live",
      statut: "a_planifier",
      notes_consultant: null,
      resultats: null,
    },
  ];

  const { data: ents, error: eErr } = await (supabase.from("entretiens") as any)
    .insert(entretiens)
    .select();
  if (eErr) throw eErr;

  // ─── 3. Chantiers ─────────────────────────────────────────
  const entretiensById: Record<string, string> = {};
  ents.forEach((e: any) => {
    entretiensById[e.service_nom] = e.id;
  });

  const chantiers = [
    {
      mission_id: mId,
      entretien_id: entretiensById["Direction des Ressources Humaines"],
      titre: "Automatisation saisie éléments variables de paie",
      description:
        "Power Automate + Microsoft Forms pour la collecte dématérialisée des éléments variables, puis injection automatique dans Sedit RH via connecteur API.",
      service_concerne: "Direction des Ressources Humaines",
      metier_source: "Gestionnaire paie",
      categorie: "automatisable",
      type_outil: "Automatisation No-Code",
      ecosysteme: "M365_PowerAutomate",
      niveau_accompagnement: "guide",
      temps_gagne_heures_semaine: 3,
      nb_personnes_impactees: 8,
      impact_total_heures_an: 1128,
      score_impact: 5,
      score_effort: 3,
      priorite: "critique",
      horizon: "3_mois",
      statut: "identifie",
      budget_estime: "8-12k€",
      prerequis: ["Licence Power Automate premium", "Connecteur Sedit API", "Validation DPO"],
      ordre: 0,
    },
    {
      mission_id: mId,
      entretien_id: entretiensById["Direction des Ressources Humaines"],
      titre: "Chatbot RH pour questions paie agents",
      description:
        "Déploiement d'un assistant Copilot M365 entraîné sur la base documentaire RH (conventions collectives, FAQ paie, notes de service) pour répondre aux questions courantes des 2400 agents.",
      service_concerne: "Direction des Ressources Humaines",
      metier_source: "Gestionnaire paie",
      categorie: "automatisable",
      type_outil: "Copilot / Assistant IA",
      ecosysteme: "M365_Copilot",
      niveau_accompagnement: "guide",
      temps_gagne_heures_semaine: 1.5,
      nb_personnes_impactees: 8,
      impact_total_heures_an: 564,
      score_impact: 4,
      score_effort: 2,
      priorite: "haute",
      horizon: "3_mois",
      statut: "identifie",
      budget_estime: "5-8k€",
      prerequis: ["Licence M365 Copilot", "Base documentaire RH structurée sur SharePoint"],
      ordre: 1,
    },
    {
      mission_id: mId,
      entretien_id: entretiensById["Direction des Ressources Humaines"],
      titre: "Contrôle automatisé pré-paie",
      description:
        "Script Python de détection d'anomalies dans les données de paie avant validation, avec dashboard Power BI de suivi des écarts.",
      service_concerne: "Direction des Ressources Humaines",
      metier_source: "Gestionnaire paie",
      categorie: "partiellement_automatisable",
      type_outil: "Script personnalisé",
      ecosysteme: "Python_Script",
      niveau_accompagnement: "consultant",
      temps_gagne_heures_semaine: 2,
      nb_personnes_impactees: 3,
      impact_total_heures_an: 282,
      score_impact: 4,
      score_effort: 4,
      priorite: "normale",
      horizon: "6_mois",
      statut: "identifie",
      budget_estime: "15-20k€",
      prerequis: ["Accès base Sedit en lecture", "Environnement Python hébergé"],
      ordre: 2,
    },
    {
      mission_id: mId,
      entretien_id: entretiensById["Direction des Finances"],
      titre: "Consolidation budgétaire automatisée",
      description:
        "Flux Power Automate pour extraire les données de Ciril Finances et les consolider automatiquement dans Power BI avec rafraîchissement planifié.",
      service_concerne: "Direction des Finances",
      metier_source: "Contrôleur de gestion",
      categorie: "automatisable",
      type_outil: "Automatisation No-Code",
      ecosysteme: "M365_PowerAutomate",
      niveau_accompagnement: "consultant",
      temps_gagne_heures_semaine: 3,
      nb_personnes_impactees: 5,
      impact_total_heures_an: 705,
      score_impact: 5,
      score_effort: 4,
      priorite: "haute",
      horizon: "6_mois",
      statut: "identifie",
      budget_estime: "20-25k€",
      prerequis: ["API Ciril Finances", "Licence Power BI Pro"],
      ordre: 3,
    },
    {
      mission_id: mId,
      entretien_id: entretiensById["Direction des Finances"],
      titre: "Dashboard direction générale",
      description:
        "Tableau de bord Power BI temps réel pour la DG, connecté aux sources Ciril et aux Excel budgétaires partagés sur SharePoint.",
      service_concerne: "Direction des Finances",
      metier_source: "Contrôleur de gestion",
      categorie: "automatisable",
      type_outil: "Automatisation No-Code",
      ecosysteme: "M365_PowerAutomate",
      niveau_accompagnement: "guide",
      temps_gagne_heures_semaine: 2,
      nb_personnes_impactees: 5,
      impact_total_heures_an: 470,
      score_impact: 3,
      score_effort: 2,
      priorite: "normale",
      horizon: "3_mois",
      statut: "identifie",
      budget_estime: "8-10k€",
      prerequis: ["Licence Power BI Pro", "Données budgétaires sur SharePoint"],
      ordre: 4,
    },
    {
      mission_id: mId,
      entretien_id: entretiensById["Direction de la Communication"],
      titre: "Agent IA de veille presse & réseaux sociaux",
      description:
        "Agent IA autonome qui surveille les mentions de la Métropole sur les réseaux sociaux et dans la presse locale, avec alertes Teams en temps réel et synthèse quotidienne.",
      service_concerne: "Direction de la Communication",
      metier_source: "Community manager",
      categorie: "automatisable",
      type_outil: "Agent IA",
      ecosysteme: "Agent_IA",
      niveau_accompagnement: "consultant",
      temps_gagne_heures_semaine: 3,
      nb_personnes_impactees: 4,
      impact_total_heures_an: 564,
      score_impact: 5,
      score_effort: 5,
      priorite: "haute",
      horizon: "6_mois",
      statut: "identifie",
      budget_estime: "25-35k€",
      prerequis: ["Accès API réseaux sociaux", "Webhook Teams", "Hébergement agent"],
      ordre: 5,
    },
    {
      mission_id: mId,
      entretien_id: entretiensById["Direction de la Communication"],
      titre: "Copilot rédaction réseaux sociaux",
      description:
        "Configuration de templates Copilot M365 avec la charte éditoriale de la Métropole pour assister la rédaction de posts LinkedIn, X et Instagram.",
      service_concerne: "Direction de la Communication",
      metier_source: "Community manager",
      categorie: "partiellement_automatisable",
      type_outil: "Copilot / Assistant IA",
      ecosysteme: "M365_Copilot",
      niveau_accompagnement: "express",
      temps_gagne_heures_semaine: 2.5,
      nb_personnes_impactees: 2,
      impact_total_heures_an: 235,
      score_impact: 3,
      score_effort: 1,
      priorite: "normale",
      horizon: "3_mois",
      statut: "identifie",
      budget_estime: "2-3k€",
      prerequis: ["Licence M365 Copilot"],
      ordre: 6,
    },
    {
      mission_id: mId,
      entretien_id: entretiensById["Direction de la Communication"],
      titre: "Revue de presse automatisée N8N",
      description:
        "Workflow N8N qui scrape les flux RSS des médias locaux, génère un résumé via LLM et l'envoie chaque matin sur le canal Teams de la direction.",
      service_concerne: "Direction de la Communication",
      metier_source: "Community manager",
      categorie: "automatisable",
      type_outil: "Workflow N8N",
      ecosysteme: "N8N",
      niveau_accompagnement: "guide",
      temps_gagne_heures_semaine: 1.5,
      nb_personnes_impactees: 4,
      impact_total_heures_an: 282,
      score_impact: 3,
      score_effort: 3,
      priorite: "normale",
      horizon: "3_mois",
      statut: "identifie",
      budget_estime: "5-8k€",
      prerequis: ["Instance N8N hébergée", "Accès flux RSS sources presse"],
      ordre: 7,
    },
  ];

  const { error: cErr } = await (supabase.from("chantiers") as any).insert(chantiers);
  if (cErr) throw cErr;

  return mId;
}
