ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS role TEXT,
  ADD COLUMN IF NOT EXISTS secteur TEXT,
  ADD COLUMN IF NOT EXISTS stack TEXT,
  ADD COLUMN IF NOT EXISTS diagnostics_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS profile_completed_at TIMESTAMPTZ;
